### ISSUE TITLE
Should register/getRegistration/getRegistrations return a new SyncRegistration instance each time

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/BackgroundSync#102]
Issue 1 in the spec.

ServiceWorker registrations are same object https://github.com/slightlyoff/ServiceWorker/issues/416#issuecomment-136599455

It's not clear from the push spec if their subscriptions should be same object, but they're not in Chrome's implementation.

**Comment by jkarlin** [comment]
Fine with me to not return the same object.

**Comment by mkruisselbrink** [comment]
Ok, I'll remove the issue from the spec, since the current algorithms already describe returning a new object.
