### ISSUE TITLE
Should sync.done reject on failure?

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/BackgroundSync#103]
I'd like to get @domenic's take on this, as it may set a precedent.

A sync registration has a `.done` promise property. A sync can fail and retry, but it will eventually terminally succeed or fail.

My gut feeling is that `.done` should reject if the operation terminally fails, as I'd expect things like `img.loaded` and `transaction.done` to do the same, but it's a grey area in terms of https://www.w3.org/2001/tag/doc/promises-guide#rejections-should-be-exceptional since it's a property.

I guess if you think of `.done` being produced by a hidden function like `waitForSyncDone()`, then rejecting makes sense.

I couldn't find any prior art here, both the font loading API & service worker's `.ready` promises never reject.

**Comment by jkarlin** [comment]
Here is a [link to the relevant part of the spec] (https://slightlyoff.github.io/BackgroundSync/spec/#dom-syncregistration-done) for @domenic.

**Comment by domenic** [comment]
I think rejecting makes some sense... true/false for something named "done" doesn't make much sense to me, certainly.

So each sync corresponds to a single sync registration object, which will reach a final state of "success" or "fail"? Or does this done promise get reset sometimes?

@TabAtkins, why does FontFaceSet's ready promise not reject if loading fails? I have some guesses but you could probably explain better.

**Comment by jkarlin** [comment]
> I think rejecting makes some sense... true/false for something named "done" doesn't make much sense to me, certainly.

Good point.

> So each sync corresponds to a single sync registration object, which will reach a final state of "success" or "fail"? Or does this done promise get reset sometimes?

It doesn't get reset.

**Comment by domenic** [comment]
OK. I am pretty convinced rejecting is sensible then.

Also, web animations uses `finished` instead of `done`; might be worth considering.

**Comment by mkruisselbrink** [comment]
OK, I'll change it to reject instead of resolve with false when sync has failed. And renaming to `finished` might make sense for consistency indeed. @jkarlin any objections to renaming the property?

**Comment by jkarlin** [comment]
Rename is fine with me.

**Comment by tabatkins** [comment]
> @TabAtkins, why does FontFaceSet's ready promise not reject if loading fails? I have some guesses but you could probably explain better.

Because it's not a situation that should throw an error.  ready() lets you know when the document is "settled" wrt font loading; failure still counts, and it's fine to go do work that depends on fonts even if all the loads fail.  It's not meant to be "let me know when everything has succeeded".
