### ISSUE TITLE
Register should work from a ServiceWorker with an uncontrolled client

### ISSUE THREAD

**Issue by jkarlin** [slightlyoff/BackgroundSync#105]
Step 3 of registration:

> If the global object specified by the incumbent settings object is a WorkerGlobalScope instance, and the serviceWorkerRegistration’s active worker is not currently controlling any clients, reject promise with an InvalidAccessError and abort these steps.

This should probably only reject if it has no clients. Uncontrolled clients should be fine, right?

**Comment by clelland** [comment]
Yes, uncontrolled clients should be okay -- as long as they're window clients, at least. That covers the case where a service worker is registered, and then immediately used to register syncs. The API shouldn't require waiting for the second page load.

**Comment by jakearchibald** [comment]
The conditions here should be the same as https://github.com/slightlyoff/BackgroundSync/issues/95 - I think any window client on the origin is fine.

**Comment by jkarlin** [comment]
Any window client on the origin works for me
