### ISSUE TITLE
API bikeshedding

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/BackgroundSync#108]
Ding ding! In the left corner we have the current API:

```js
swReg.sync.register({
  tag: tagName
}).then(reg => {
  // registration worked!
  reg.unregister();
});

swReg.sync.getRegistration(tagName).then(reg => {
  // …
});

swReg.sync.getRegistrations().then(regs => {
  // regs - sequence of registrations
});
```

And in the right corner, a simpler proposal by @martinthomson:

```js
swReg.sync.register(tagName).then(() => {
  // registration worked!
});

swReg.sync.unregister(tagName).then(didUnregister => {
  // didUnregister - was there an actual sync to unregister?
});

swReg.sync.getTagNames().then(tagNames => {
  // tagNames - sequence of tag names
});
```

![fight](https://cloud.githubusercontent.com/assets/93594/10916553/3d6b46be-825c-11e5-91ae-2046ee9ef638.png)

**Comment by jakearchibald** [comment]
The simpler API covers everything we need right now, but may land us in trouble if we want to extend later on. For example, if we wanted to add `.finished` back, we'd need a registration object to put it on. That means `unregister` would be in the wrong place, `getTagNames` seems a little useless, and we'd have to add `getRegistration` and `getRegistrations`.

"finishing" couldn't be added to the `.register()` return promise, as it gets tough to tell the difference between unsuccessful sync and unable-to-register.

Having registration objects also matches the push API, if that matters.

However, I kinda like taking tag name the first argument, and requiring it.

**Comment by clelland** [comment]
> For example, if we wanted to add .finished back, we'd need a registration object to put it on.

Not necessarily -- we could attach that to the sync manager, like unregister:

    swReg.sync.whenFinished(tagName).then(success => {
        // sync is finished - did it succeed?
    });

**Comment by jkarlin** [comment]
An issue with `SyncRegistration` is that it becomes stale once the registration has completed. The simpler API can only refer to existing registrations.

**Comment by martinthomson** [comment]
Is there any need to cancel a sync?  Or, rather, any need to retract a request for sync?

I ask because I see this as an exceptional condition, and one that might be better dealt with by persisting a "don't bother" state.  I know that we want to minimize the number of calls into the service worker, but sync is already being called only when convenient, so I don't see a problem with an occasional no-op sync being triggered.

If there are use cases where cancellation is commonplace, then a registration remains as a good idea.

As for the point that @jakearchibald regarding `.finished`, I think that recovering the state of requested sync requests is interesting, but again, I'm struggling to justify this based on the limited set of use cases that I've looked at.  An application can use its own signaling to recover this sort of state.  This is advanced enough that I think we could justify asking applications to work this out for themselves.

**Comment by jakearchibald** [comment]
> Is there any need to cancel a sync? Or, rather, any need to retract a request for sync?

I don't see it being common. If you delete all pending messages from the outbox you may want to cancel the sync, although as you point out it isn't exactly disastrous if that sync still happens.

Syncs are cancellable by the user/browser, eg if the user revokes the ability for an origin to carry out any background activity. From an extensible web standpoint it seems that cancellation should be doable via script too.

> As for the point that @jakearchibald regarding .finished, I think that recovering the state of requested sync requests is interesting, but again, I'm struggling to justify this based on the limited set of use cases that I've looked at. An application can use its own signaling to recover this sort of state. This is advanced enough that I think we could justify asking applications to work this out for themselves.

Yeah, we've dropped `.finished` because of this. We'll add it back once/if we can identify the common patterns it would be useful for.

**Comment by jkarlin** [comment]
> Not necessarily -- we could attach that to the sync manager, like unregister:
```swReg.sync.whenFinished(tagName).then(success => {
    // sync is finished - did it succeed?
});```

The difference is that you can't query for an already finished sync this way if the tag has been reregistered. So it wouldn't give us quite the same functionality.

If we remove unregister then it seems pretty silly to return an empty registration object. If we want to add a registration object in the future could we just change:

`Promise<null> register(tag)` to `Promise<SyncRegistration> register(tag)`? Or would that be too breaking?

I still think that getRegistrations() is useful for debugging.

**Comment by mkruisselbrink** [comment]
Going from `Promise<void>` to `Promise<SyncRegistration>` seems like it should be a safe change to make in the future. Going from `void` to `Promise<...>` is generally the problematic case, but that doesn't apply here since we'd have a promise anyway.

**Comment by jkarlin** [comment]
Well, if we can add `Promise<SyncRegistration>` later then it seems reasonable to remove it for now.

So, how does this look?

```javascript
interface SyncManager {
  Promise<void> register(DOMString tag);
  Promise<sequence<DOMString>> getRegisteredTags();
};
```

**Comment by mkruisselbrink** [comment]
I think that looks good. I'll make those changes tomorrow unless somebody else beats me to it.

**Comment by jkarlin** [comment]
sgtm

**Comment by clelland** [comment]
This also means that SyncEvent should look like

    [Constructor(DOMString type, SyncEventInit init), Exposed=ServiceWorker]
    interface SyncEvent : ExtendableEvent {
      readonly attribute DOMString tag;
      readonly attribute boolean lastChance;
    };
