### ISSUE TITLE
Advice for developers

### ISSUE THREAD

**Issue by annevk** [slightlyoff/BackgroundSync#17]
We should maybe add some advice.

There's many apps on my phone that have background updates. When I open the app I see something interesting which within seconds is replaced by "newer" content and I can no longer find what I was looking at. This is rather annoying behavior.

**Comment by jakearchibald** [comment]
I don't think this is the right home for this, you're more likely to create this poor experience with the `fetch` event. http://jakearchibald.com/2014/offline-cookbook/#cache-then-network

**Comment by annevk** [comment]
Well if you only used the cache and `fetch` at least nothing would change in the background that then quickly disappears while the user tries to read these background updates.

**Comment by jakearchibald** [comment]
Nothing will change visually in either case unless some page-based code modifies the DOM.

I think this is important stuff & it really annoys me when native apps get it wrong, but it's usually down to active app code rather than background processing.

**Comment by annevk** [comment]
Without background processing when you leave and when you come back to it will have roughly the same state which will then get quickly obsoleted due to network activity.

With background processing when you leave and when you come back will not have the same state. So not only are you seeing surprising items when you come back, they are quickly obsoleted too due to further network activity.

Of course, both are up to developers to make sure they behave better, but I would argue that the second is worse.

**Comment by jkarlin** [comment]
I think best practices are a good to have, and could be in the explainer or developer documentation. I don't see this going in the spec though. Okay to close this issue?

**Comment by annevk** [comment]
It's fairly common for specifications to give some usage advice, no?

**Comment by jakearchibald** [comment]
Doesn't do any harm, but I think this spec is the wrong place for this very-much-foreground bit of advice

**Comment by jkarlin** [comment]
Agree that this is foreground advice.
