### ISSUE TITLE
Match the sync API with the more established Push API

### ISSUE THREAD

**Issue by jkarlin** [slightlyoff/BackgroundSync#20]
We should follow in the footsteps of [Push](https://w3c.github.io/push-api/) and move navigator.sync to serviceworker.syncManager.  Here is some proposed IDL:

```javascript
partial interface ServiceWorkerRegistration {
    readonly attribute SyncManager syncManager;
};

interface SyncManager {
    Promise register(string id, optional SyncRegistrationOptions);
    Promise<bool> unregister(string id);
    Promise<vector<string>> getRegistrations();
    Promise<SyncPermissionStatus> hasPermission ();
};

interface SyncRegistrationOptions {
    attribute int minInterval;
    attribute bool repeating;
    attribute string data;  // bytes instead?
    attribute string description;
    attribute string lang;
    attribute string dir;
};

partial interface ServiceWorkerGlobalScope {
                attribute EventHandler onsync;
};
```

Thoughts?

**Comment by annevk** [comment]
I think it should be allowed if permission is granted, indeed. The Notification API does something similar (it has its own permission API that's simply not available in service worker, but the idea is the same).

**Comment by jkarlin** [comment]
I worry about one-shots being able to continuously reregister themselves if we allow one-shot registration from a worker. The user may give permission for one-shots without the expectation that they behave like periodic.

**Comment by johnmellor** [comment]
It'll frequently be more convenient to schedule one-shots from a SW (for analytics, error reporting, and even core use cases like sending email/chats when next online), even when the SW is acting on behalf of a foreground document.

Instead, how about we allow one-shots if and only if the following query is resolved with a non-empty list of clients:
<pre>
clients.matchAll({
    includeUncontrolled: true,
    <a href="https://github.com/slightlyoff/ServiceWorker/issues/626">includeEvicted</a>: false
})
</pre>

**Comment by johnmellor** [comment]
And I guess we should also allow them if you have permission for periodic sync (though it makes for a slightly awkward API, where sites may have to request and then cancel a periodic sync just to be able to use one-shot sync).

**Comment by annevk** [comment]
Only allowing one-shot when there's an open window seems fine, even when permission is granted for periodic... Especially as we have two distinct APIs anyway it seems best to keep them internally consistent.

**Comment by jkarlin** [comment]
Allowing one-shot only with an open window sgtm too.

**Comment by KenjiBaheux** [comment]
Sounds reasonable.

One thing I was curious about, in the "at least one open window" test, do we care about differentiating between at least one controlled client (includeUncontrolled: false) or any potential client (includeUncontrolled: true).

I guess it boils down to "Would the user expectations differs between these 2 options"?
A SW that's active but not controlling a page would still get PushEvent and I imagine SyncEvent, so it doesn't seem like user expectations should differ, right?

**Comment by annevk** [comment]
The existence of a service worker is transparent to the user. The only thing they notice is the site offering some synchronization of push functionality, so I'd think that any open window would be okay. (Though if user agents offer UI to opt out they should make sure to offer that on all windows of the origin, not just those controlled by a service worker.)

**Comment by jkarlin** [comment]
This is now captured in the spec.
