### ISSUE TITLE
Expose registration options?

### ISSUE THREAD

**Issue by annevk** [slightlyoff/BackgroundSync#30]
Currently you cannot inspect the registration. So in your code you need to keep track of what options belong to what ID. Oftentimes I think we reach the conclusion that we would like to be able to inspect those values which would argue for a slightly different design here.

E.g. we could introduce a `SyncRegistration` object that you construct with an ID and options and you would register that object (and `getRegistrations` would return copies of them).

**Comment by mvano** [comment]
Agreed. We do this for the Push API. This also makes the API easier to extend in future.

**Comment by jkarlin** [comment]
Sounds good to me.

**Comment by jkarlin** [comment]
annevk: can you create a patch?
