### ISSUE TITLE
What should promises resolve with?

### ISSUE THREAD

**Issue by clelland** [slightlyoff/BackgroundSync#31]
`syncManager.register` and `syncManager.unregister` currently return promises resolving to booleans. There's no mention in the spec of what these booleans mean. I don't think they should refer to success/failure -- the promise's fate already covers that.

Should we change that to something like

      Promise<SyncRegistrationOptions> register(DOMString id, optional SyncRegistrationOptions options);
      Promise<void> unregister(DOMString id);

And `register` can return the options that were actually stored (in case they were modified by the user agent.) Or just have both return void promises?

**Comment by jakearchibald** [comment]
In the push spec, `unsubscribe` resolves with a boolean indicating if anything was actually unsubscribed. Maybe that's useful here too?

`register` should resolve with undefined, or some kind of object that represents registration state (which could have similar properties to `SyncRegistrationOptions`. When would `register` resolve with different options than the ones you pass in?

**Comment by jkarlin** [comment]
Agree that a bool is useful for unregister.

We've discussed the option of using a chooser for sync. A dialog with text like,  "How often would you like this page to be able to sync in the background? Once a day, twice a day, weekly, never" would pop up on a call to register. If we did that, then returning the parameters in a SyncRegistrationOptions would be useful.

I think returning the SyncRegistrationOptions is at least not harmful, and potentially useful in the future. +1

**Comment by clelland** [comment]
@jakearchibald  -- In your unregister scenario, then, does syncManager.unregister("non-existing-sync-event-id") resolve with false, rather than rejecting? If so, could it ever reject?

**Comment by mvano** [comment]
For `unregister` see also the Push API: https://w3c.github.io/push-api/#pushsubscription-interface

I think these similar APIs should avoid being different without cause.

**Comment by jakearchibald** [comment]
@clelland 

> In your unregister scenario, then, does syncManager.unregister("non-existing-sync-event-id") resolve with false, rather than rejecting? If so, could it ever reject?

Yeah, it would resolve with false. Once `syncManager.unregister("non-existing-sync-event-id")` resolves, there is no registration with ID "non-existing-sync-event-id". Ok, there never was one, but that doesn't feel exceptional. Eg, `clearTimeout(nonExistingID)` does not throw.

However, @mvano makes a very good point. Push & ServiceWorker itself doesn't have `unregister(id)`, it has `registration.unregister()`. Makes sense to be the sync up* here.

* this pun will never, ever get old

**Comment by annevk** [comment]
I think what we do here depends on the outcome of #30. We don't really need to resolve with anything if we end up exposing the individual registrations.

**Comment by jkarlin** [comment]
Resolved. unregister returns a boolean in the spec. True if successful false if it wasn't found.
