### ISSUE TITLE
Critical battery condition: leave it up to the user agent.

### ISSUE THREAD

**Issue by KenjiBaheux** [slightlyoff/BackgroundSync#33]
Some native platform block (native) background sync operations when the device is operating under critical battery conditions. 

The spec might want to note that the user agent has the freedom to do so (e.g. "the user agent may ignore pending bg sync requests if the device is operating under critical battery conditions").

**Comment by jakearchibald** [comment]
sgtm. We still need `allowOnBattery` though, right?

**Comment by jkarlin** [comment]
sgtm as well. Can you create a pull request Kenji?

**Comment by KenjiBaheux** [comment]
@jakearchibald yes, we still need that option.
@jkarlin can you assign me? Or better yet, give me rights to assign and add labels (it's been useful for ServiceWorker :) ).

**Comment by jkarlin** [comment]
@slightlyoff can you give Kenji the permissions?
