### ISSUE TITLE
Location tracking

### ISSUE THREAD

**Issue by annevk** [slightlyoff/BackgroundSync#36]
Per use-cases.md this is an issue.

I guess the rationale behind this being a concern is that the assumption is that a service worker implementation does not upgrade in the background, but only when a site is actually visited (or just prior, given "good" heuristics).

This seems like something the UX should make clear to the user when opting into this feature. I don't think there's anything we can do beyond that, right?

**Comment by jkarlin** [comment]
We can do a bit more than a permission. For one-shots with a minDelay of 0, we could pop up a notification until the one-shot resolves with accept. This way the user knows that something is happening in the background, and when it completes. I think it will give them a more intuitive understanding of the privacy risk and they'll know when their email has sent. This is just like a background download on Android.  

An option for periodic is to have a chooser, "How often would you like to let this site sync in the background? daily, twice a day, weekly, never". It puts control in the user's hands and makes them think a bit about the ramifications.

**Comment by jkarlin** [comment]
Closing this as I think there is agreement that the UAs need to be careful with regard to user privacy here.

**Comment by annevk** [comment]
Yes, but this does need to be called out somewhere. (Can I get edit issue permissions?)

**Comment by jkarlin** [comment]
@slightlyoff can you please give @annevk permissions.

**Comment by jkarlin** [comment]
This is called out in the spec. Closing as fixed.
