### ISSUE TITLE
Alarm API

### ISSUE THREAD

**Issue by annevk** [slightlyoff/BackgroundSync#38]
The use cases document mentions this.

There is http://www.w3.org/TR/2013/WD-web-alarms-20130205/ (latest version link is broken) written by @cdumez.

The web obviously needs something like this so we can have https://clock.org/ and https://calendar.org/ and https://reminders.org/ all be applications that have the same capabilities as native.

The question is however whether background synchronization is the right place to address this. Or whether that should be a similar API but with a distinct opt in.

**Comment by clelland** [comment]
They would certainly have a very similar API, but I don't think that's sufficient reason to make them part of the same platform feature.

Is it better for the web if the developers's model for background sync is always "These events are coalesced, and you can't guarantee that they're even going to happen"?

(The question is important -- the exact alarms use cases are certainly on [the list](../blob/master/use-cases.md) and part of the reason for that is to consider whether they're even in scope for this API)

**Comment by annevk** [comment]
Seems like we're saying the same thing. For what it's worth, given that alarms require precision and require to be activated at the precise moment I'm inclined to think they are different from synchronization.

Main thing I'm struggling with is UX.

**Comment by jakearchibald** [comment]
I've always though of them as being a separate api too.

If we tackle one-off sync first, then vague sync, then precise, we can
tackle the UX starting easiest-first

**Comment by jkarlin** [comment]
Agree, alarms are for another API. Closing the issue.

**Comment by annevk** [comment]
Shouldn't the use cases document be amended first in this case? This issue was filed for a reason...
