### ISSUE TITLE
Minimal API surface needed to start solving one-off sync use cases?

### ISSUE THREAD

**Issue by KenjiBaheux** [slightlyoff/BackgroundSync#42]
Could we try to scope and design the API in a way that let us solve a good chunk of the use cases without precluding the resolution of the remaining use cases (i.e. Minimal Viable Product)? 

The one-off sync use cases seems simpler than the periodic sync use cases which should make them easier to design for.

What would be the minimal viable surface we need to solve a good chunk of the one-off sync use cases as explained in https://github.com/slightlyoff/BackgroundSync/blob/master/use-cases.md ?

**Comment by KenjiBaheux** [comment]
Let me give it a shot:
```
partial interface ServiceWorkerRegistration {
  readonly attribute SyncManager syncManager;
};

interface SyncManager {
  Promise<SyncRegistration> register();
};

interface SyncRegistration {
};

partial interface ServiceWorkerGlobalScope {
  attribute EventHandler onsync;
};```

Is this the bare minimum we would need to allow for one-off sync in the following scenario:
 - you want to do signal your interest in being able to do some work at the next online opportunity
 - you don't have multiple type of work (so no need for an id)
 - if it so happens that you had the opportunity to do that work before the onsync, you can just no-op in your onsync handler (so no need for unregister)
 - you don't have any fancy requirements around when the sync should happen and are entirely ok with a best-effort basis (e.g. by not specifying any options you leave it up to the user agent to do what's best for the user: assumes online, can make own judgment about Wi-Fi vs. mobile / battery vs AC /..., a 'default'/empty id*)
 - being able to do some work at the next online opportunity is  seen as nice to have addition. So it's good enough for you to know from the promise if the registration worked or not (so no need for hasPermission)
 - since you only have one type of sync work, you don't need getRegistrations
 

I also assumed that you wouldn't need creating onsync event so I took these out.
One thing I'm not sure about: do we need to decide between Promise<SyncRegistration> register vs. Promise register at this stage or can it happen later?

**Comment by annevk** [comment]
> if it so happens that you had the opportunity to do that work before the onsync, you can just no-op in your onsync handler (so no need for unregister)

That makes it rely on UA heuristics whether or not the event will dispatch and be listened for. I rather not do that. 

It seems you also want to check whether you already registered something. And this makes it impossible to require an ID, see #41.

**Comment by annevk** [comment]
Perhaps we should have different APIs for different use cases. As far as I can tell we have need for these kind of APIs:

* wake-when-online (sync)
* wake-when-online-periodically (refresh)
* wake-at-time (alarm)
* wake-at-times (calendar)

And then from elsewhere we have:

* wake-on-notificationclick (notification)
* wake-on-push (push)

Having them distinct we could each do fairly minimally. And then let UAs experiment how they want to deal with permissions for each of them. I could imagine UAs grouping some of these behind a single permission.

**Comment by jkarlin** [comment]
Oh, I also think we need unregister() as it's easy to add and can still be useful.

Proposed IDL:
``` javascript
partial interface ServiceWorkerRegistration {
  readonly attribute SyncManager syncManager;
};

interface SyncManager {
  Promise<SyncRegistration> register(SyncRegistration);
  Promise<boolean> unregister();
};

interface SyncRegistration {
  DOMString id;
};

partial interface ServiceWorkerGlobalScope {
  attribute EventHandler onsync;
};

dictionary SyncEventInit : EventInit {
  required SyncRegistration registration;
};

[Constructor(DOMString type, SyncEventInit eventInitDict), Exposed=ServiceWorker]
interface SyncEvent : ExtendableEvent {
  readonly attribute SyncRegistration registration;
};
```

**Comment by annevk** [comment]
`unregister()` should not be on `SyncManager`.

I wonder if we split the use cases whether developers will need multiple disjoint synchronization strategies. Also, you can say that the difference is `minPeriod` but this is also about UX and expectations. And how these are likely to evolve going forward.

**Comment by annevk** [comment]
Also, `register()` should not take a `SyncRegistration` object. How would you even get one with that IDL?

**Comment by jkarlin** [comment]
My bad. End of the day. Thanks annevk.  Updated IDL:

``` javascript
partial interface ServiceWorkerRegistration {
  readonly attribute SyncManager syncManager;
};

interface SyncManager {
  Promise<SyncRegistration> register(DOMString id);
  Promise<sequence<SyncRegistration>> getRegistrations();
};

interface SyncRegistration {
  readonly attribute DOMString id;
  Promise<boolean> unregister();
};

partial interface ServiceWorkerGlobalScope {
  attribute EventHandler onsync;
};

dictionary SyncEventInit : EventInit {
  required SyncRegistration registration;
};

[Constructor(DOMString type, SyncEventInit eventInitDict), Exposed=ServiceWorker]
interface SyncEvent : ExtendableEvent {
  readonly attribute SyncRegistration registration;
};
```

**Comment by jkarlin** [comment]
In regards to multiple APIs: Let's start with the one-shot and `register()`. If we decide that periodic needs to be its own API then we can add `registerPeriodic()` later.

**Comment by KenjiBaheux** [comment]
Oh, the last sentence in my comment is completely meaningless. I meant to say Promise returning a SyncRegistration or Promisevreturning nothing. I guess that if we believe that id and/or unregister are critical or important yet low risk then returning a SyncRegistration object is critical.


 @jkarlin can you explain why id and unregister are critical or important yet low risk in terms of solving a specific set of use cases?

**Comment by jkarlin** [comment]
`id` and `unregister` are certainly low risk in terms of implementation. `id` should be there a) because it allows for multiple events, each with a different task and b) because once we add the rest of the API it will be required. Unregister should be there because it's incomplete not to have it and it's low risk to add it. Unregister brings with it getRegistrations(). Again, low risk. The higher risk things are the various options to register() that we're excluding for now.

**Comment by KenjiBaheux** [comment]
OK, I imagine that adding these 3 items should not add much in terms of risk (e.g. ranging from bikesheding to design decisions) and we can always revisit the scope if it turns out to be a source of controversy.

Anne, does this MVP IDL sounds reasonable?
If so, let's focus on specifying the details of this MVP IDL and get agreement from interested parties (web developers and browser folks)!

**Comment by annevk** [comment]
It's unclear to me why you would want multiple events given that they would all dispatch at the same time. That's why I argued you might want distinct APIs, since wake-when-online is really a one-off.

**Comment by jkarlin** [comment]
After discussion in #41 I'm okay with @KenjiBaheux 's original IDL, which has less surface area. We'll use an empty string as the default ID.

@annevk Don't we eventually want to add options to the one-shot though? Like min start time, wifi only, etc? In which case we'll want IDs.

**Comment by annevk** [comment]
I don't know. We don't have any use cases that require that.

**Comment by jkarlin** [comment]
I'm in favor now of two registration functions, one for oneshot and one for periodic. As @annevk  said earlier, this allows each to have its own permission behavior. We'll also need to handle two permissions with hasPermission.

**Comment by KenjiBaheux** [comment]
I think we can close this issue.
