### ISSUE TITLE
Add getRegistration(DOMString id) to SyncManager

### ISSUE THREAD

**Issue by jkarlin** [slightlyoff/BackgroundSync#43]
In order to unregister a registration you first need to get a hold of the SyncRegistration object. To do that you have to call `registrations()` and then search the returned list. It seems like we should provide a `getRegistration(DOMString id)` in SyncManager as well.

**Comment by jkarlin** [comment]
Or we could keep add back the old `SyncManager.unregister(id)` as a convenience API.

**Comment by annevk** [comment]
I think the former solution is better if this is needed often. You might want the object for other reasons.
