### ISSUE TITLE
Should sync event target a specific server?

### ISSUE THREAD

**Issue by imintz** [slightlyoff/BackgroundSync#46]
Considering that most use cases will want to communicate with a specific server once they become online, should SyncRegistrationOptions also allow the user to specify a server to ensure connectivity to that specific target?

**Comment by jkarlin** [comment]
This could be a nice optimization. By default, I could imagine the UA verifying connectivity to the SW's origin. Do you think a dev-specified server is necessary above and beyond that?

**Comment by annevk** [comment]
If we want certain DNS entries to be recent that seems like something that's reasonable to have for the service worker as a whole.

**Comment by jkarlin** [comment]
Is there a need for a dev-specified server in any use cases?

**Comment by annevk** [comment]
Well I would imagine you `importScripts()` stuff could be on a CDN. As well as large video resources and such your service worker might deal with. Or perhaps the external Flickr API domain in the Trained to Thrill application. But as I said in my comment, those use cases are for service workers in general.

**Comment by imintz** [comment]
The main use case that I think this applies to is with packaged apps and Cordova implementations of service worker. In those cases, we'd want the spec to be identical, but the service worker's origin is local and so you can't really use it as a target for checking connectivity.

**Comment by jkarlin** [comment]
annevk@ I see, so perhaps the UA might try to do some DNS resolving while spinning up the ServiceWorker. Or, in the case of a sync event that requires connectivity, it would actually preconnect before starting the SW.

**Comment by KenjiBaheux** [comment]
Would having the UA learn about connection patterns be enough? Or would we gain a lot more by having a dev-specified list of servers to prewarm for?

**Comment by KenjiBaheux** [comment]
Oh, should we move this to the Service worker github issue tracker?

**Comment by annevk** [comment]
Moving this seems fine. Analysis would probably be a good first step for implementations actually. (That gives you the cache with DNS entries and such... Letting it be populated by the site can then come later.)

**Comment by KenjiBaheux** [comment]
This issue was moved to slightlyoff/ServiceWorker#644

**Comment by jakearchibald** [comment]
I'm not sure we should have moved this… I'm not sure if this could be a generic SW feature.
