### ISSUE TITLE
USVString instead of DOMString for id

### ISSUE THREAD

**Issue by jkarlin** [slightlyoff/BackgroundSync#51]
I know this has come up somewhere before, but now that I'm implementing, having a non-utf8 compliant string is painful as I need to store the id to disk and potentially may want to sync across devices in the future. Can we switch to USVString?

**Comment by annevk** [comment]
I would rather not. We don't do this for IDB either. We should really use USVString only when URLs or a protocol is involved that requires utf-8.

**Comment by jkarlin** [comment]
What is the use case for DOMString anyway? What do we lose with USVString?

**Comment by annevk** [comment]
It's more a principle. When there's no need for USVString we shouldn't use it and stay true to JavaScript strings.

**Comment by jkarlin** [comment]
Okay, sgtm.
