### ISSUE TITLE
Two permissions, two APIs

### ISSUE THREAD

**Issue by jkarlin** [slightlyoff/BackgroundSync#52]
It seems like one-shots and periodic ought to have separate permissions at the API level (the UA can merge them or do whatever it will behind the scenes).  In which case, we should probably have two API functions. Which means we need names. I proposing, `register(id, options)` and `registerPeriodic(id, minPeriod, options)`.  Any reason not to make the options the same for both?

Then we also need ways to check on those permissions. We could rely on the web permissions API for that but we don't want to delay others browsers from implementing sync by having to first implement web permissions. So should there be two `hasPermission()` calls as well? E.g., `hasPermission()` and `hasPeriodicPermission()` or should `hasPermission()` just return both values?

**Comment by annevk** [comment]
It's probably more convenient to have separate methods for figuring out the permission level.

I'm not sure why id became a required argument again. I thought there was agreement for it to default to the empty string.

**Comment by jkarlin** [comment]
My bad, id is optional. I think two permissions calls is good. I'm not so sure that I like having separate functions for `register` and `getRegistrations` though. What do y'all think?

```javascript
interface SyncManager {
  Promise<SyncRegistration> register(optional SyncRegistrationOptions options);
  Promise<SyncPeriodicRegistration> registerPeriodic(unsigned long minPeriod, optional SyncRegistrationOptions options);
  Promise<sequence<SyncRegistration>> getRegistrations();
  Promise<sequence<SyncPeriodicRegistration>> getPeriodicRegistrations();
  Promise<SyncPermissionStatus> hasPermission();
  Promise<SyncPermissionStatus> hasRepeatingPermission();
  readonly attribute unsigned long minAllowablePeriod;
};
```

vs

```javascript
interface SyncManager {
  Promise<SyncRegistration> register(optional SyncRegistrationOptions options);
  Promise<sequence<SyncRegistration>> getRegistrations();
  Promise<SyncPermissionStatus> hasPermission();
  Promise<SyncPermissionStatus> hasPeriodicPermission();
  readonly attribute unsigned long minAllowablePeriod;
};
```

**Comment by jkarlin** [comment]
Of course, if the registration options don't match between the two of them, then we have no choice but to have two sets of functions.

**Comment by annevk** [comment]
What about `.sync` and `.periodicSync` that both return a `SyncManager` that is nearly identical?

**Comment by annevk** [comment]
I would be happy to not have any options for the one-shot for now (and also less options for the other). We might want to indicate in the draft what possible extensions might be so implementers take that under consideration... I think in general for this feature we need to see some experimentation happening.

**Comment by jakearchibald** [comment]
Given the use-cases for one-off and period sync are totally different, I agree with @annevk that these should be kept entirely separate, including the event they trigger in the SW - `sync` vs `periodicsync`.

I think `id` is still useful for one-off, but agree we can drop the rest of the options for MVP.

**Comment by jkarlin** [comment]
Okay so `.sync` and `.periodicSync` return `SyncManager` and `PeriodicSyncManager` with separate onsync and onperiodicsync events. SGTM.
