### ISSUE TITLE
Should minAllowablePeriod be an async request?

### ISSUE THREAD

**Issue by clelland** [slightlyoff/BackgroundSync#55]
Currently in the IDL, `SyncManager.minAllowablePeriod` is just an exposed constant.

Are there any conceivable situations where this could be dynamic, or take longer than a couple of ms to return a value? If so, then maybe we should make it an async call, something like

    Promise<unsigned long> minAllowablePeriod

and it can be a promise -- for now, one that immediately resolves with the right value, but potentially slower in the future.

(I don't think that we should -- I think that, even if it could take a while to return, it will only be used by apps on startup, never in a loop, and making it async just complicates their startup logic. However, if we're ever going to want to make it async, then we should do it now)

**Comment by KenjiBaheux** [comment]
Could it be dynamic in the sense that it depends on who is asking for it (e.g. to let the user agent arbitrate opportunities among the different customers based on track record / user value)?

**Comment by clelland** [comment]
It could be, certainly -- whether it _should_ be probably depends on how much of a promise this is to the requesting site, and what this constant actually means.

Does this represent the minimum period that the user agent will *ever* allow? Or the minimum period that the requesting site will be permitted to use? Even that shouldn't be guaranteed, I think -- we may one day decide to let the user determine the actual period at request time.

I *think* that it's the first -- the lower limit that the browser will ever resolve. If that's the case, then a constant should be okay. The site should always be checking the value returned from the `register()` promise anyway, if it really cares.

**Comment by jakearchibald** [comment]
What's the use-case for `minAllowablePeriod`? Since `minPeriod` is a hint to avoid over-firing, a site setting this to 0 for "as often as the UA deems appropriate" seems ok.

`minPeriod: 24 * 60 * 60 * 1000` is the developer saying "please don't fire this more frequently than roughly once a day as there's no benefit or my server can't take it".

**Comment by jkarlin** [comment]
Different platforms and different UAs will have different values for how often they might sync. Desktop might let you fire every minute while mobile fires no more than once every 8 hours. Providing the minimum value to the developer lets them decide if and how to use periodic sync.

**Comment by jakearchibald** [comment]
What would the developer do with this?

If we keep this, I don't think we should reject if a registration call has a number less than this. I think `minPeriod:0` is useful for "as often as the UA deems appropriate".

**Comment by jkarlin** [comment]
Not register a periodic sync because it's not going to be frequent enough and not worth prompting for a permission?

Agree that minPeriod:0 is useful.

**Comment by jakearchibald** [comment]
> Not register a periodic sync because it's not going to be frequent enough and not worth prompting for a permission?

Given this, a dynamic value would be inappropriate, so `minAllowablePeriod` (or `minPossiblePeriod`?) can be a synchronous property?

**Comment by jkarlin** [comment]
I think this really comes down to the spirit of periodic sync. If we want to give developers an expectation of when they can sync (understanding that sometimes it's delayed) then minPeriod is useful. If it's completely up in the air when syncs will happen then perhaps we don't need it.

**Comment by jkarlin** [comment]
It appears that synchronous is preferred.
