### ISSUE TITLE
PSA: W3C Community Group

### ISSUE THREAD

**Issue by jkarlin** [slightlyoff/BackgroundSync#57]
We have a [W3C Community Group](https://www.w3.org/community/blog/2015/03/04/proposed-group-web-background-sync-community-group/). Please support it and sign up!

**Comment by annevk** [comment]
That's a CG, not a WG... If we just want to do FSA snapshots, we could do that through e.g. the WHATWG CG as well.

**Comment by jkarlin** [comment]
Whoops, yes, CG. Fixed. Any particular reason to do WHATWG instead? My understanding is that it's easier for some organizations to partake in W3C. Push and SW are also W3C.

**Comment by annevk** [comment]
Push and SW are in WG. The WHATWG has a CG: https://www.w3.org/community/whatwg/

**Comment by jkarlin** [comment]
I obviously know little about the standards process. My plan was to create a CG for background sync where we'll put together a draft specification. Then hopefully a WG (such as WebApps) will adopt it and publish it. Is that reasonable?

**Comment by annevk** [comment]
You don't really need to create a CG for that. Just develop a draft and propose it to WebApps. You might have to wait for charter updates, but perhaps it can be in scope because SW is in scope.

**Comment by jkarlin** [comment]
Okay, in which case the only reason to have the CG is if it encourages other organizations to contribute. Let's reach out and see.

**Comment by jkarlin** [comment]
I suppose we could just communicate over public-webapps@ for that like Service Workers does.

**Comment by annevk** [comment]
Yeah, that seems preferable.

**Comment by KenjiBaheux** [comment]
https://github.com/slightlyoff/BackgroundSync/issues/57#issuecomment-77194538 makes sense.

The community group has graduated from the proposed list: https://www.w3.org/community/bgsync/
 I assume there is no harm in keeping the CG in case we need it. 

Tentatively closing.
