### ISSUE TITLE
What does network-any mean?

### ISSUE THREAD

**Issue by clelland** [slightlyoff/BackgroundSync#61]
I can see two possible interpretations of `minRequiredNetwork: "network-any"`, and I think that either of them is redundant.

1. `network-any` means "Any network state" -- this is supported by its position in the enum, but I think it's identical to `network-offline` (Unless there's a state with even *less* than offline-access -- maybe `network-card-ripped-out-and-dangling-from-the-cable`?)

2. `network-any` means "Some (any) network is available" -- this would be identical to `network-online`, as far as I can tell.

Is there another distinction that I'm just not seeing right now, or should one of these be removed from the IDL?

**Comment by jkarlin** [comment]
I think it can go.
