### ISSUE TITLE
Rename 'id' to 'tag'

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/BackgroundSync#64]
This brings consistency with [notifications](https://notifications.spec.whatwg.org/#dom-notification-tag), since the intent is similar (unless I'm mistaken)

**Comment by KenjiBaheux** [comment]
Sounds good from my read of [this section](https://notifications.spec.whatwg.org/#using-the-tag-member-for-a-single-instance).

**Comment by jakearchibald** [comment]
Should an empty tag also count as a tag?

```js
sync.register({tag: 'hello'});
sync.register({tag: 'hello'});
```

…will only create one registration. Should the same be true of:

```js
sync.register();
sync.register();
```

**Comment by annevk** [comment]
Yes.

**Comment by jkarlin** [comment]
It is 'tag' in the spec.
