### ISSUE TITLE
minRequiredNetwork & netinfo

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/BackgroundSync#65]
The netinfo API [goes with "cellular"](http://w3c.github.io/netinfo/#idl-def-ConnectionType) rather than mobile.

If there a use-case for offline sync? If not, maybe this should become a boolean such as `avoidCellularConnection` or similar.

**Comment by jkarlin** [comment]
Agree on cellular

**Comment by KenjiBaheux** [comment]
Here is one use case for offline "sync":
 I own a third party service that provide assets to various customers websites.
 I might want to register for a periodic sync (e.g. idle, once a week, network connectivity optional) to rationalize the assets storage (e.g. prune less frequently used assets).

**Comment by jkarlin** [comment]
Another is to process new pictures in storage so that the next time a photo app is opened they're already ready for viewing.

**Comment by jkarlin** [comment]
Closing as the original issue is between cellular and mobile and we went with cellular. 

The offline cases are relevant to #77
