### ISSUE TITLE
Is idleRequired encouraging battery draining?

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/BackgroundSync#73]
Given that a phone likes to shut down the radio etc when it's idle, is restricting sync to this situation doing more harm than good?

**Comment by KenjiBaheux** [comment]
I think the use case is for when you want to do bandwidth hungry and/or computation heavy tasks while avoiding grinding the user experience to a halt. 

Killing the battery would equally be a bad outcome.

Can the UA arbitrate these requests based on past outcomes for a given origin x scope?

**Comment by annevk** [comment]
I think we should leave this out. The UA should already optimize for doing synchronization when it impacts the user as little as possible (both performance and battery-wise).

**Comment by jkarlin** [comment]
+1 for leaving it to the UA for now.

**Comment by jakearchibald** [comment]
It's not in the latest explainer or IDL, so job done!
