### ISSUE TITLE
TaskScheduler API tackles the exact timer problem

### ISSUE THREAD

**Issue by jkarlin** [slightlyoff/BackgroundSync#75]
http://www.w3.org/2012/sysapps/web-alarms/

It looks like it was updated last October and now uses ServiceWorkers. We should coordinate with them.

**Comment by annevk** [comment]
@maheshkk and @cdumez, thoughts?

**Comment by annevk** [comment]
How is this not #38 btw?

**Comment by jkarlin** [comment]
My bad, this is indeed a dupe of #38.
