### ISSUE TITLE
Persistent storage for one-off sync

### ISSUE THREAD

**Issue by annevk** [slightlyoff/BackgroundSync#79]
Applications might not want UI to get persistent storage. So maybe we should give sites a small bucket to store some data in a persistent manner for one-off synchronization. We would make it a writeonly bucket that only can be transferred so it cannot be abused much.

This in part depends of course on the UI for one-off synchronization and maybe it does not even need to be tied to that necessarily, but I wanted to log this somewhere.

**Comment by jakearchibald** [comment]
I'm unable to wrap my head around this. Why is IDB the wrong thing to use here?

**Comment by jkarlin** [comment]
To make a one-shot persistent we'd also have to make the service worker registration persistent until the one-shot fires.

**Comment by jkarlin** [comment]
Note that from personal experience I think people will be using CacheStorage and not IDB to transfer data between the document and sync event. And use the 'tag' as a pointer into the storage or just put the data in the tag itself. Do we need to specify a max tag length?

**Comment by jakearchibald** [comment]
I'm less confident about the use of the likelyhood of cache API usage here. The cache API is request/response, and a background sync tends to involve a request that doesn't have a response. You'd have to hack the cache API a bit to do it.

(although I've seen people hack the cache API into a key/val store because it's simpler to use than IDB)

**Comment by jkarlin** [comment]
That's what I did, I used it as a key/value store. And put the key in the bgsync tag. IDB is a pain.

**Comment by annevk** [comment]
IDB and the Cache API are both non-persistent by default. The idea is to have some kind of new API that can be used to store a small amount of synchronization data that we guarantee to keep around for a long time (unless the user manually clears storage/cookies, of course).

**Comment by jkarlin** [comment]
This is an interesting idea, though I'm not sure one-shot warrants truly persistent storage. Are you okay  with closing this issue as it's ultimately an issue for another API?

**Comment by annevk** [comment]
Sure.
