### ISSUE TITLE
Add secure context checks

### ISSUE THREAD

**Issue by annevk** [slightlyoff/BackgroundSync#90]
`register()` should probably be guarded, maybe more?

**Comment by mkruisselbrink** [comment]
I wasn't sure about this. On one hand the dependency on service workers and the fact that the api is only available via ServiceWorkerRegistration already mostly guarantees this only works in secure context, but it might indeed be better to make that explicit at least for register.

**Comment by annevk** [comment]
Well, you expose the API on `Window`. How is that guarded?

**Comment by mkruisselbrink** [comment]
To call the background sync api you need to get access to a ServiceWorkerRegistration first, and that guarantees at least some level of secure origin. But I agree that that indeed isn't as strong as requiring a secure context, so I'll add an explicit requirement for that in register.

**Comment by annevk** [comment]
That might in fact be enough then, actually.

**Comment by annevk** [comment]
Can you envision a scenario in which an insecure context gets hold of that?

**Comment by mkruisselbrink** [comment]
It's the difference between a secure context and a secure/trustworthy origin that allows that. Iframes with a secure origin that are embedded in an insecure website are not considered a secure context, yet the service worker spec is a bit unclear what if any of the SW functionality should be available to these iframes.

So even if "Service workers should execute in secure contexts, and the controlled service worker clients should also be secure contexts. " is followed exactly in an implementation, an uncontrolled iframe which isn't considered a secure context (but has a secure origin) will still have access to all the ServiceWorkerRegistrations that are registered at the same origin as the iframe. Maybe that's something that should be fixed/clarified on the service worker side though?

**Comment by annevk** [comment]
Yeah, that should be fixed first. Was talking to @mikewest about that earlier today. His thoughts were that a `https://service.example/` would not have access to its service worker when embedded in an insecure context.

**Comment by mikewest** [comment]
I think that's what the nightly spec's security considerations section says should happen.

**Comment by mkruisselbrink** [comment]
The current nightly service worker spec seems very unclear about what exactly should and shouldn't be allowed. All it says is "Service workers should execute in secure contexts, and the controlled service worker clients should also be secure contexts. " which doesn't exactly address if insecure context iframes can be uncontrolled clients, nor if they should have access to any service worker registrations. (also why is that a "should" and not a "must"?)

Also none of the methods/algorithms mention what should happen when they are called in an insecure context... Should I file a bug on the SW spec to get this clarified/worked out?

**Comment by annevk** [comment]
Sure.

**Comment by jkarlin** [comment]
Can this be closed?

**Comment by mkruisselbrink** [comment]
I think so yes. With how the SW issue seems to be going to be resolved, I don't think there is anything else that needs to be added to this spec.
