### ISSUE TITLE
"In the background"

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/BackgroundSync#95]
> The sync event is considered to run in the background if the user agent is either closed or no service worker clients (controlled or uncontrolled) exist for the corresponding service worker registration.

Since this definition is being used for security/privacy, would this do:

> The sync event is considered to run in the background if no window clients exist for the origin of the corresponding service worker registration.

The changes I'm trying to make here:

* There must be window clients - if only shared worker clients are hanging around for whatever reason, the sync would be considered background
* If the controlled state doesn't matter, it's the "scope" we're talking about, but…
* Origins are the web's security boundary - so should we just use those?

**Comment by clelland** [comment]
I feel like 'scope' makes sense here -- Origin isn't the only security boundary for the web, (I feel scopes are more akin to cookie domain/path boundaries, anyway). Syncs are registered from the context of a SW, and handled by that SW, and I don't know if it makes sense for other web apps, in different scopes on the same origin, to affect whether this one is 'in the background' or not.

**Comment by jakearchibald** [comment]
> Origin isn't the only security boundary for the web, (I feel scopes are more akin to cookie domain/path boundaries, anyway)

But an out-of-scope page can still get hold of all SW registrations and do things like register for push messages.

**Comment by jkarlin** [comment]
Origin sounds good. I've copied jakearchibald@'s text from comment 1 verbatim in pull request #106.
