### ISSUE TITLE
Allow registration even if there are no controlled pages

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/BackgroundSync#98]
1. User visits site
2. SW registered
3. SW installs
4. SW activates
5. User submits message
6. Background sync registration fails

This is due to step 2 in https://slightlyoff.github.io/BackgroundSync/spec/#sync-manager-interface

> If the global object specified by the incumbent settings object is a WorkerGlobalScope instance, and the serviceWorkerRegistration’s active worker is not currently controlling any clients, reject promise with an InvalidAccessError and abort these steps.

Step 5 of https://w3c.github.io/push-api/#widl-PushManager-subscribe-Promise-PushSubscription--PushSubscriptionOptions-options seems to set precedent here, but we'd also want to ensure there's a window client existing for the origin.

**Comment by jkarlin** [comment]
>If the global object specified by the incumbent settings object is a WorkerGlobalScope instance, and the serviceWorkerRegistration’s active worker is not currently controlling any clients, reject promise with an InvalidAccessError and abort these steps.

This only applies to WorkGlobalScope contexts, not documents.

**Comment by jakearchibald** [comment]
Wow, can't believe I missed that. Sorry.

**Comment by jakearchibald** [comment]
Moved the non-stupid bits into https://github.com/slightlyoff/BackgroundSync/issues/98
